export enum ROUTES {
  CHANGE_PASSWORD = "change-password",
  SET_PASSWORD = "set-password",
  OBJECTIVES = "objectives",
  ORGANIZATION = "organization",
  HOME = "/",
  TEAMS = "teams",
  PEOPLE = "people",
  PROFILE = "profile",
  LOGIN = "login",
  OKR = "okr",
  OKR_DETAIL = "okr/:id",
  SETTING = "setting",
  TIMEPERIOD = "timeperiod",
  UNAUTHORIZED = "unauthorized",
  WELCOME = "welcome",
  Setting = "setting",
  FORGOT_PASSWORD = "forgot-password",
}
